bcgov/epic-engage

.github/workflows/analytics-api-cd.yml
.github/workflows/met-api-cd.yml
.github/workflows/met-cron-cd.yml
.github/workflows/met-etl-cd.yml
.github/workflows/met-web-cd.yml
.github/workflows/notify-api-cd.yml

Changes to update repo url

---

met-etl/src/etl_project/services/ops/survey_etl_service.py

Issue #: https://github.com/bcgov/epic-engage/issues/3

Fix for maintaining likert kinda survey position

---

met-api/src/met_api/services/survey_service.py
met-web/src/components/survey/building/index.tsx

Enabled editing of surveys for published engagements

---

met-etl/src/etl_project/services/ops/survey_etl_service.py

added survey id changing for updated surveys

---

met-etl/src/etl_project/services/ops/survey_etl_service.py

survey updated with new survey id

---

analytics-api/src/analytics_api/models/request_type_option.py

- Addressed bug causing incorrect survey results after editing. The issue stemmed from the dynamic update of the request ID in the form JSON upon survey editing. This fix removes the dependency on the request ID, replacing it with the constant key column, ensuring consistent behavior even after survey edits.

Update Join from Request ID to Key

---

met-api/src/met_api/models/comment.py
met-api/src/met_api/services/comment_service.py
met-web/src/components/engagement/dashboard/comment/CommentTable.tsx
met-web/src/components/engagement/dashboard/comment/CommentViewContext.tsx

Issue #: https://github.com/bcgov/epic-engage/issues/22
- Back end changes to pull the question along with the comment
- Front end changes to format the report to group submissions and display the comments with the associated question

Display comments on the report with associated question

---

met-web/src/components/layout/SideNav/UserGuideNav.tsx

Updated the EPIC Engage Guide Link

---

met-cron/requirements.txt

Linking requirement to Epic Engage

---

met-api/templates/email_rejected_comment_closed.html
met-web/src/components/comments/admin/review/emailPreview/EmailPreview.tsx

Updating rejection email, removing an unwanted comma.

Updating rejection email

---

met-web/src/components/engagement/view/EmailModal.tsx
met-web/src/components/engagement/view/EngagementView.tsx
met-web/src/components/engagement/view/widgets/Subscribe/EmailListModal.tsx
met-web/src/components/survey/submit/ActionContext.tsx
met-web/src/routes/PageViewTracker.tsx

Add in error handling for snowplow.

Add in error handling for snowplow

---

met-web/src/locales/en/eao.json

EPICSYSTEM-69
Update listed contact person on comment review page.

[EPICSYSTEM-69] Update contact on comment review page.

---

met-web/src/components/engagement/view/FailurePanel.tsx
met-web/src/components/engagement/view/widgets/Subscribe/EmailListModal.tsx

Issue #: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-68
Changed email placeholders to the correct EAO emails.

EPICSYSTEM-68 Updated email placeholders to correct emails

---

met-etl/src/etl_project/services/ops/submission_etl_service.py

#13 
[ECPISYSTEM-62]
Edit submission etl service to not skip all values that are falsy. eg. radio buttons that have 0 as a legitimate value.

[EPICSYSTEM-62] add support for falsy submission values in etl

---

met-web/src/routes/NotFound.tsx

EPICSYSTEM-70 - remove placeholder email

---

met-web/src/components/survey/create/CloneOptions.tsx
met-web/src/components/survey/create/LinkOptions.tsx
met-web/src/components/survey/create/OptionsForm.tsx

Load surveys before radio buttons are selected to reduce load time

EPICSYSTEM-61: Select survey to clone/attach drop-downs take too long to load

---

met-web/src/components/publicDashboard/SurveyBar/SurveyBarBlock.tsx
met-web/src/components/publicDashboard/SurveyBar/TooltipContent.tsx
met-web/src/components/publicDashboard/SurveyBar/TreemapBlock.tsx
met-web/src/components/publicDashboard/SurveyBar/TreemapLabel.tsx
met-web/src/components/publicDashboard/SurveyBarPrintable/index.tsx

Fixed both bar graph and tree map display of survey question responses
Fixed PDF export display

EPICSYSTEM-60: fixed how surveys with large number of answers display

---

met-api/src/met_api/models/comment.py

https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-82
Order comments in public/proponent export by id

order public/proponent comment export by id

---

met-web/src/components/publicDashboard/util.ts

https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-63
Add geoJSON data to map when exporting engagement data

[EPICSYSTEM-63]: Add project spatial info to PDF export

---

met-web/package-lock.json
met-web/package.json
met-web/src/components/layout/Footer/constants.ts
met-web/src/components/layout/Footer/index.tsx

Issue 76: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-76
Remove Facebook and Instagram icons
Update twitter icon and lin

[EPICSYSEM-76] update social media icons and links

---

met-api/src/met_api/services/email_verification_service.py

Issue 125: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-125?
Add token in response for rejected emails

add verification token in for rejection email

---

met-web/src/components/engagement/form/ActionContext.tsx

Issue #81: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-81
Show save confirmation even when no data has changed

[EPICSYSTEM-81] show save confirmation message on every save click

---

met-web/src/components/engagement/view/FailurePanel.tsx

fix email typo in failure panel

---

met-web/src/components/survey/report/ReportSettingsContext.tsx

Issue #64: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-64
Surveys that had a 'simplesurvey' question require slightly different logic for sorting to match form order

allow for sorting of simplesurvey questions

---

met-web/public/index.html

- Changed title to display EPIC.engage 
- Changed content to updated text for EAO

EPICSYSTEM-10: Change title and content text

---

met-web/package-lock.json
met-web/package.json

Issue 72: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-72
Update formio/react page to allow for page reordering of surveys

[EPICSYSTEM-72] form builder page reordering

---

met-web/src/components/common/Modals/types.tsx
met-web/src/components/engagement/view/FailurePanel.tsx
met-web/src/components/engagement/view/widgets/Subscribe/EmailListModal.tsx
met-web/src/routes/NotFound.tsx

Issue #: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-129
make support links clickable mailtos

[EPICSYSTEM-129]: make support links mailto

---

met-etl/Dockerfile
met-etl/container/user_code/Dockerfile

Issue #: https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-231
- Updated the version for dagster.

Bug fix for dagster etl error

---

met-api/src/met_api/services/survey_service.py

fixing lint issues

---

met-web/src/components/layout/Footer/index.tsx

Issue #:  https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-170
Move X icon and link above divider

ES-170: footer changes

---

met-api/src/met_api/models/survey.py

fix submission page error for extended end date

---

met-api/requirements.txt

bug fix for map widget

---

met-web/src/components/publicDashboard/SurveyBarPrintable/index.tsx

fix labels on pdf export

---

met-api/src/met_api/resources/engagement_settings.py
met-web/src/components/engagement/view/ActionContext.tsx
met-web/src/components/engagement/view/SurveyBlock.tsx

Hide 'View Feedback' when send report is false

---

met-web/src/locales/en/eao.json

Issue #: https://eao-dst.atlassian.net/jira/software/c/projects/ENGAGE/boards/11?selectedIssue=ENGAGE-57
Updating the contact email/name for when threat is flagged in a comment

[ENGAGE-57] Change threat contact
